### ISSUE TITLE
about JAI error

### ISSUE THREAD

**Issue by abhid95** [mpillar/java-emotion-recognizer#2]
[javac] /home/ubuntu/Desktop/java-emotion-recognizer-master/src/app/EmotionRecognitionApplication.java:7: error: package javax.media.jai does not exist
    [javac] import javax.media.jai.*;
    [javac] ^

I installed jai in my linux 64 bit using instructions given [here](http://docs.geoserver.org/latest/en/user/production/java.html#installing-native-jai-on-linux)
still same error!!
Could u pls tell what might be the reason?
Thank u

**Comment by daleysoftware** [comment]
Hey @abhid95, sorry to say that I don't have experience with JAI installation on Linux. I'd advise you to contact the JAI maintainers if you have questions in this area.
